;;theme settings
(setq-default tab-width 4)
(setq-default cursor-type 'bar)
(setq initial-frame-alist (quote ((fullscreen . maximized))))
(tool-bar-mode -1)
(global-hl-line-mode 1)
(scroll-bar-mode -1)
(load-theme 'spacemacs-light t)
(nyan-mode)
(spaceline-spacemacs-theme)
(provide 'init-theme)
